Repository max2023-4th-project-01/BE-B-Cokkiri-Market, pull requests merged in 2023-10, with the labels that each got.

#88 fix: 기본 이미지가 삭제되던 에러 수정 #87
  be/src/main/java/kr/codesquad/category/dto/response/FavoriteCategoryResponse.java
  be/src/main/java/kr/codesquad/core/config/RedisConfig.java
  be/src/main/java/kr/codesquad/core/config/SecurityWebSocketConfig.java
  be/src/main/java/kr/codesquad/core/filter/WebSocketInterceptor.java
  be/src/main/java/kr/codesquad/image/service/AmazonS3Service.java
  be/src/main/java/kr/codesquad/util/Constants.java
Labels: bug, fix

#86 fix: item image 더미데이터 추가 및 도커 컨테이너 시간 설정
  be/src/main/resources/data.sql
  docker-compose.yml
Labels: fix, release

#93 관심 목록 페이지에서 하트수 조회 쿼리 수정
  be/src/main/java/kr/codesquad/item/repository/ItemPaginationRepository.java
Labels: bug, fix, be

#92 feat: 조회수 처리, 아이템 수정 불러오기 변경
  be/src/main/java/kr/codesquad/category/dto/response/CategoryEditResponse.java
  be/src/main/java/kr/codesquad/category/service/CategoryService.java
  be/src/main/java/kr/codesquad/core/filter/WebSocketInterceptor.java
  be/src/main/java/kr/codesquad/item/controller/ItemController.java
  be/src/main/java/kr/codesquad/item/dto/response/ItemDetailResponse.java
  be/src/main/java/kr/codesquad/item/dto/response/ItemUpdateResponse.java
  be/src/main/java/kr/codesquad/item/dto/vo/ItemListVo.java
  be/src/main/java/kr/codesquad/item/entity/Item.java
  be/src/main/java/kr/codesquad/item/repository/ItemPaginationRepository.java
  be/src/main/java/kr/codesquad/item/repository/ItemRepository.java
  be/src/main/java/kr/codesquad/item/service/ItemService.java
  be/src/main/java/kr/codesquad/location/dto/response/LocationResponse.java
  be/src/main/java/kr/codesquad/location/repository/LocationRepository.java
  be/src/main/resources/application-dev.yml
  be/src/main/resources/schema.sql
  be/src/test/java/kr/codesquad/repository/ItemRepositoryTest.java
  be/src/test/java/kr/codesquad/repository/LocationRepositoryTest.java
  be/src/test/java/kr/codesquad/service/UserServiceTest.java
Labels: feat, be

#95 feat: 채팅 목록 조회 기능 구현 #89
  be/src/main/java/kr/codesquad/chat/controller/ChatController.java
  be/src/main/java/kr/codesquad/chat/dto/response/ChatMemberDataResponse.java
  be/src/main/java/kr/codesquad/chat/dto/response/ChatRoomListResponse.java
  be/src/main/java/kr/codesquad/chat/dto/response/ItemDataResponse.java
  be/src/main/java/kr/codesquad/chat/dto/response/UserChatRoomListResponse.java
  be/src/main/java/kr/codesquad/chat/dto/vo/ChatMessageCountDataVo.java
  be/src/main/java/kr/codesquad/chat/dto/vo/ChatRoomListVo.java
  be/src/main/java/kr/codesquad/chat/entity/ChatMessage.java
  be/src/main/java/kr/codesquad/chat/repository/ChatRoomListRepository.java
  be/src/main/java/kr/codesquad/chat/service/ChatService.java
  be/src/main/java/kr/codesquad/core/config/WebSocketConfig.java
Labels: feat

#97 fix: 로케이션 목록 불러오기 오류 수정
  be/src/main/java/kr/codesquad/item/service/ItemService.java
  be/src/main/java/kr/codesquad/location/service/LocationService.java
Labels: bug, fix

#98 채팅 기능 수정
  be/src/main/java/kr/codesquad/chat/controller/ChatController.java
  be/src/main/java/kr/codesquad/chat/dto/ChatMapper.java
  be/src/main/java/kr/codesquad/chat/dto/request/ChatMessageRequest.java
  be/src/main/java/kr/codesquad/chat/dto/request/SendMessageRequest.java
  be/src/main/java/kr/codesquad/chat/dto/response/ChatRoomDetailResponse.java
  be/src/main/java/kr/codesquad/chat/repository/ChatRoomListRepository.java
  be/src/main/java/kr/codesquad/chat/repository/ChatRoomRepository.java
  be/src/main/java/kr/codesquad/chat/service/ChatService.java
  be/src/main/java/kr/codesquad/core/config/SecurityConfig.java
  be/src/main/java/kr/codesquad/core/config/SecurityWebSocketConfig.java
  be/src/main/java/kr/codesquad/core/config/WebSocketConfig.java
  be/src/main/java/kr/codesquad/core/filter/AuthorizationFilter.java
  be/src/main/java/kr/codesquad/core/filter/WebSocketInterceptor.java
  be/src/main/java/kr/codesquad/item/dto/response/ItemDetailResponse.java
  be/src/main/java/kr/codesquad/item/service/ItemService.java
  be/src/main/java/kr/codesquad/user/repository/UserRepository.java
Labels: feat, be

#101 Dev fe
  package-lock.json
  package.json
  server.js
  src/App.tsx
  src/api/axios.ts
  src/api/endPoint.ts
  src/api/fetchers/chatFetcher.ts
  src/api/queries/useChatQuery.ts
  src/api/queries/useItemQuery.ts
  src/api/queries/useLocationQuery.ts
  src/components/Layout.tsx
  src/components/ProductItem.tsx
  src/components/SlidePanel.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/SignUpLocationModal.tsx
  src/hooks/useGetDropdownDirection.ts
  src/hooks/useWebSocket.ts
  src/mocks/chatHandlers.ts
  src/mocks/handlers.ts
  src/page/Chatting.tsx
  src/page/Favorites.tsx
  src/page/ItemDetails.tsx
  src/page/SalesList.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/chat/ChatRoom.tsx
  src/page/chat/ChattingItem.tsx
  src/page/chat/ChattingList.tsx
  src/page/chat/Message.tsx
  src/page/home/Home.tsx
  src/page/productEditor/ProductEditorPanel.tsx
  src/stores/usePanelStore.ts
  src/stores/useScreenConfigStore.ts
  src/utils/addCommasToNumber.ts
  src/utils/priceToString.ts
Labels: fe
