Repository max2023-4th-project-01/BE-B-Cokkiri-Market, pull requests merged in 2023-09, with the labels that each got.

#19 상품 목록 조회 기능 구현
  be/build.gradle
  be/src/main/java/kr/codesquad/config/QueryDslConfig.java
  be/src/main/java/kr/codesquad/filter/AuthorizationFilter.java
  be/src/main/java/kr/codesquad/item/controller/ItemController.java
  be/src/main/java/kr/codesquad/item/dto/CustomSlice.java
  be/src/main/java/kr/codesquad/item/dto/ItemListResponse.java
  be/src/main/java/kr/codesquad/item/dto/ItemListVo.java
  be/src/main/java/kr/codesquad/item/dto/ItemMapper.java
  be/src/main/java/kr/codesquad/item/dto/ItemRequest.java
  be/src/main/java/kr/codesquad/item/dto/ItemResponse.java
  be/src/main/java/kr/codesquad/item/repository/ItemPaginationRepository.java
  be/src/main/java/kr/codesquad/item/service/ItemService.java
Labels: feat

#10 BE용 CI/CD 환경 설정
  .github/workflows/cd-pipeline.yml
  .github/workflows/cicd-be.yml
  .github/workflows/cicd-fe.yml
  be/Dockerfile
  be/src/main/java/kr/codesquad/config/SecurityConfig.java
  be/src/main/resources/application-dev.yml
  be/src/main/resources/application.yml
  docker-compose.yml
  nginx/nginx.conf
Labels: feat

#21 fe 브랜치에 infra/cicd-fe 브랜치 머지
  .github/workflows/cicd-fe.yml
  Dockerfile
  docker-compose.yml
  nginx/nginx.conf
  package.json
  src/App.tsx
  src/components/Layout.tsx
  src/components/Modal.tsx
  src/main.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/stores/useScreenConfigStore.ts
  src/styles/reset.css
Labels: fe

#25 동네 CRUD
  README.md
  be/src/main/java/kr/codesquad/category/entity/Category.java
  be/src/main/java/kr/codesquad/item/service/ItemService.java
  be/src/main/java/kr/codesquad/location/controller/LocationController.java
  be/src/main/java/kr/codesquad/location/dto/request/LocationCreateRequest.java
  be/src/main/java/kr/codesquad/location/dto/response/LocationListResponse.java
  be/src/main/java/kr/codesquad/location/entity/Location.java
  be/src/main/java/kr/codesquad/location/repository/LocationRepository.java
  be/src/main/java/kr/codesquad/location/service/LocationService.java
  be/src/main/java/kr/codesquad/user/controller/UserController.java
  be/src/main/java/kr/codesquad/user/service/UserService.java
  be/src/main/java/kr/codesquad/util/CategoryDataInit.java
  be/src/main/resources/application-dev.yml
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: feat

#29 fe 레포에서 커밋 기록 가져오기
  package-lock.json
  package.json
  src/App.tsx
  src/api/endPoint.ts
  src/api/fetcher.ts
  src/assets/image/sad_elephant.png
  src/components/Error.tsx
  src/components/Header.tsx
  src/components/Modal.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/LocationButton.tsx
  src/components/locations/LocationModal.tsx
  src/components/locations/SetLocation.tsx
  src/mocks/authHandlers.ts
  src/mocks/locationHandlers.ts
  src/page/auth/LoginPage.tsx
  src/page/auth/MyAccount.tsx
  src/page/auth/MyProfilePage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
  src/queries/useLocationQuery.ts
  src/stores/useScreenConfigStore.ts
  src/types.ts
Labels: fe

#30 fe 배포 테스트
  package-lock.json
  package.json
  src/App.tsx
  src/api/endPoint.ts
  src/api/fetcher.ts
  src/assets/image/sad_elephant.png
  src/components/Error.tsx
  src/components/Header.tsx
  src/components/Modal.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/LocationButton.tsx
  src/components/locations/LocationModal.tsx
  src/components/locations/SetLocation.tsx
  src/mocks/authHandlers.ts
  src/mocks/locationHandlers.ts
  src/page/auth/LoginPage.tsx
  src/page/auth/MyAccount.tsx
  src/page/auth/MyProfilePage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
  src/queries/useLocationQuery.ts
  src/stores/useScreenConfigStore.ts
  src/types.ts
Labels: fe

#28 feat: 커스텀 예외 생성 #27
  be/src/main/java/kr/codesquad/core/error/CustomException.java
  be/src/main/java/kr/codesquad/core/error/ErrorResponse.java
  be/src/main/java/kr/codesquad/core/error/GlobalExceptionHandler.java
  be/src/main/java/kr/codesquad/core/error/statuscode/ErrorCode.java
  be/src/main/java/kr/codesquad/core/error/statuscode/StatusCode.java
  be/src/main/resources/application.yml
Labels: feat

#33 Feat/image upload
  .github/workflows/cicd-be.yml
  be/build.gradle
  be/src/main/java/kr/codesquad/core/config/AwsS3Config.java
  be/src/main/java/kr/codesquad/core/error/ErrorResponse.java
  be/src/main/java/kr/codesquad/core/error/statuscode/FileErrorCode.java
  be/src/main/java/kr/codesquad/image/service/AmazonS3Service.java
  be/src/main/resources/application.yml
Labels: feat

#34 판매내역, 관심 품목 목록 조회
  be/src/main/java/kr/codesquad/auth/service/OAuthService.java
  be/src/main/java/kr/codesquad/category/dto/CategoryMapper.java
  be/src/main/java/kr/codesquad/category/dto/response/FavoriteCategoryResponse.java
  be/src/main/java/kr/codesquad/core/config/SecurityConfig.java
  be/src/main/java/kr/codesquad/core/filter/AuthorizationFilter.java
  be/src/main/java/kr/codesquad/favorite/repository/FavoriteDslRespository.java
  be/src/main/java/kr/codesquad/favorite/service/FavoriteService.java
  be/src/main/java/kr/codesquad/item/controller/ItemController.java
  be/src/main/java/kr/codesquad/item/dto/CustomSlice.java
  be/src/main/java/kr/codesquad/item/dto/ItemMapper.java
  be/src/main/java/kr/codesquad/item/dto/response/UserItemListResponse.java
  be/src/main/java/kr/codesquad/item/dto/slice/ItemListSlice.java
  be/src/main/java/kr/codesquad/item/dto/slice/UserItemListSlice.java
  be/src/main/java/kr/codesquad/item/dto/vo/ItemListVo.java
  be/src/main/java/kr/codesquad/item/entity/ItemConditions.java
  be/src/main/java/kr/codesquad/item/repository/ItemPaginationRepository.java
  be/src/main/java/kr/codesquad/item/service/ItemService.java
  be/src/main/java/kr/codesquad/jwt/service/JwtAuthenticationSuccessHandler.java
  be/src/main/java/kr/codesquad/user/controller/UserController.java
  be/src/main/java/kr/codesquad/util/Constants.java
Labels: feat

#37 Infra/cicd fe 에서 fe 로 배포 테스트
  Dockerfile
  package-lock.json
  package.json
  src/App.tsx
  src/api/authFetcher.ts
  src/api/fetcher.ts
  src/components/Alert.tsx
  src/components/Button.tsx
  src/components/button/Button.tsx
  src/components/button/TextButton.tsx
  src/components/icon/Icon.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/LocationButton.tsx
  src/components/locations/LocationModal.tsx
  src/components/locations/SetLocation.tsx
  src/mocks/authHandlers.ts
  src/mocks/locationHandlers.ts
  src/page/Test.tsx
  src/page/auth/AuthInput.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/MyAccount.tsx
  src/page/auth/MyProfilePage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/auth/authConstant.ts
  src/page/home/CategoryFilterPanel.tsx
  src/queries/useLocationQuery.ts
  src/stores/useAuthStore.ts
  src/types.ts
  src/utils/localStorage.ts
Labels: fe

#39 로그인 회원가입 기능 추가 및 수정
  be/src/main/java/kr/codesquad/auth/service/OAuthService.java
  be/src/main/java/kr/codesquad/core/filter/AuthorizationFilter.java
  be/src/main/java/kr/codesquad/item/service/ItemService.java
  be/src/main/java/kr/codesquad/jwt/service/JwtAuthenticationSuccessHandler.java
  be/src/main/java/kr/codesquad/user/controller/UserController.java
  be/src/main/java/kr/codesquad/user/dto/UserMapper.java
  be/src/main/java/kr/codesquad/user/dto/request/UserSignUpRequest.java
  be/src/main/java/kr/codesquad/user/entity/User.java
  be/src/main/java/kr/codesquad/user/repository/UserRepository.java
  be/src/main/java/kr/codesquad/user/service/UserService.java
Labels: feat

#42 좋아요 기능 구현
  be/src/main/java/kr/codesquad/core/error/statuscode/FavoriteErrorCode.java
  be/src/main/java/kr/codesquad/favorite/controller/FavoriteController.java
  be/src/main/java/kr/codesquad/favorite/dto/request/FavoriteUpdateRequest.java
  be/src/main/java/kr/codesquad/favorite/dto/response/FavoriteUpdateResponse.java
  be/src/main/java/kr/codesquad/favorite/repository/FavoriteRepository.java
  be/src/main/java/kr/codesquad/favorite/service/FavoriteService.java
Labels: feat

#47 fe 배포 테스트
  src/api/authFetcher.ts
  src/api/axios.ts
  src/api/fetcher.ts
  src/api/locationFetcher.ts
  src/api/mainFetcher.ts
  src/assets/image/icon_accessories.png
  src/assets/image/icon_appliance.png
  src/assets/image/icon_baby.png
  src/assets/image/icon_beauty.png
  src/assets/image/icon_book.png
  src/assets/image/icon_car.png
  src/assets/image/icon_clothes.png
  src/assets/image/icon_digital.png
  src/assets/image/icon_etc.png
  src/assets/image/icon_food.png
  src/assets/image/icon_furniture.png
  src/assets/image/icon_hobby.png
  src/assets/image/icon_kitchen.png
  src/assets/image/icon_man.png
  src/assets/image/icon_pet.png
  src/assets/image/icon_plant.png
  src/assets/image/icon_sports.png
  src/assets/image/icon_ticket.png
  src/assets/image/index.ts
  src/components/Error.tsx
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/Loader.tsx
  src/components/ProductItem.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/MenuItem.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/HomeLocationModal.tsx
  src/components/locations/SetLocation.tsx
  src/components/locations/SignUpLocationModal.tsx
  src/hooks/useDebounceValue.ts
  src/hooks/useScrollLock.ts
  src/main.tsx
  src/mocks/faker.ts
  src/mocks/locationHandlers.ts
  src/mocks/mainHandlers.ts
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
  src/queries/useItemQuery.ts
  src/queries/useLocationQuery.ts
  src/stores/useAuthStore.ts
  src/styles/designSystem.ts
  src/types.ts
Labels: fe

#53 fe 데이터
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/endPoint.ts
  src/api/mainFetcher.ts
  src/hooks/useDebounceValue.ts
  src/mocks/faker.ts
  src/mocks/handlers.ts
  src/mocks/mainHandlers.ts
  src/page/home/Home.tsx
Labels: fe

#54 3주차 fe 배포 테스트 2nd
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/endPoint.ts
  src/api/mainFetcher.ts
  src/hooks/useDebounceValue.ts
  src/mocks/faker.ts
  src/mocks/handlers.ts
  src/mocks/mainHandlers.ts
  src/page/home/Home.tsx
Labels: fe

#56 fix: Refresh-Token 설정 추가 #55
  be/src/main/java/kr/codesquad/core/config/SecurityConfig.java
  be/src/main/java/kr/codesquad/jwt/service/JwtAuthenticationSuccessHandler.java
  be/src/main/java/kr/codesquad/util/Constants.java
Labels: fix

#60 infra/cicd-fe
  src/App.tsx
  src/api/axios.ts
  src/api/endPoint.ts
  src/api/itemFetcher.ts
  src/api/mainFetcher.ts
  src/api/queries/useItemQuery.ts
  src/api/queries/useLocationQuery.ts
  src/components/Badge.tsx
  src/components/Footer.tsx
  src/components/Loader.tsx
  src/components/ProductItem.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/HomeLocationModal.tsx
  src/components/locations/LocationButton.tsx
  src/components/locations/SetLocation.tsx
  src/mocks/faker.ts
  src/mocks/handlers.ts
  src/mocks/itemsHandlers.ts
  src/mocks/locationHandlers.ts
  src/page/Favorites.tsx
  src/page/SalesList.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/OAuthLoading.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
  src/queries/useItemQuery.ts
  src/types.ts
Labels: fe

#61 fe QA 반영
  src/App.tsx
  src/api/axios.ts
  src/api/endPoint.ts
  src/api/itemFetcher.ts
  src/api/mainFetcher.ts
  src/api/queries/useItemQuery.ts
  src/api/queries/useLocationQuery.ts
  src/components/Badge.tsx
  src/components/Footer.tsx
  src/components/Loader.tsx
  src/components/ProductItem.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/HomeLocationModal.tsx
  src/components/locations/LocationButton.tsx
  src/components/locations/SetLocation.tsx
  src/mocks/faker.ts
  src/mocks/handlers.ts
  src/mocks/itemsHandlers.ts
  src/mocks/locationHandlers.ts
  src/page/Favorites.tsx
  src/page/SalesList.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/OAuthLoading.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
  src/queries/useItemQuery.ts
  src/types.ts
Labels: fe, release

#58 fix: detail에 Exception 상세 출력하도록 수정 #27
  be/build.gradle
  be/src/main/java/kr/codesquad/core/error/GlobalExceptionHandler.java
  be/src/main/java/kr/codesquad/util/Constants.java
Labels: fix, build

#62 feat: 테스트 코드 초기 설정 #59
  be/src/main/java/kr/codesquad/category/entity/Category.java
  be/src/main/java/kr/codesquad/favorite/dto/request/FavoriteUpdateRequest.java
  be/src/main/java/kr/codesquad/favorite/dto/response/FavoriteUpdateResponse.java
  be/src/main/resources/application-dev.yml
  be/src/main/resources/application.yml
  be/src/test/java/kr/codesquad/IntegrationTestSupport.java
  be/src/test/java/kr/codesquad/repository/FavoriteRepositoryTest.java
  be/src/test/java/kr/codesquad/service/FavoriteServiceTest.java
Labels: feat, test

#63 test: favoriteRepositoryTest 작성 #59
  be/src/test/java/kr/codesquad/repository/FavoriteRepositoryTest.java
Labels: test

#68 4주차 프론트 배포 테스트
  src/App.tsx
  src/api/fetchers/authFetcher.ts
  src/api/fetchers/itemDetailsFetcher.ts
  src/api/fetchers/itemFetcher.ts
  src/api/fetchers/locationFetcher.ts
  src/api/queries/useItemDetailsQuery.ts
  src/api/queries/useItemQuery.ts
  src/api/queries/useLocationQuery.ts
  src/components/Badge.tsx
  src/components/Header.tsx
  src/components/ProductItem.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/MenuItem.tsx
  src/components/itemDetails/ImageSlider.tsx
  src/mocks/handlers.ts
  src/mocks/itemDetailsHandlers.ts
  src/mocks/itemsHandlers.ts
  src/mocks/locationHandlers.ts
  src/page/ItemDetails.tsx
  src/page/Test.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
Labels: fe, release

#71 프론트 4주차 배포
  src/App.tsx
  src/api/fetchers/authFetcher.ts
  src/api/fetchers/itemDetailsFetcher.ts
  src/api/fetchers/itemFetcher.ts
  src/api/fetchers/locationFetcher.ts
  src/api/queries/useItemDetailsQuery.ts
  src/api/queries/useItemQuery.ts
  src/api/queries/useLocationQuery.ts
  src/components/Badge.tsx
  src/components/Header.tsx
  src/components/ProductItem.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/MenuItem.tsx
  src/components/itemDetails/ImageSlider.tsx
  src/mocks/handlers.ts
  src/mocks/itemDetailsHandlers.ts
  src/mocks/itemsHandlers.ts
  src/mocks/locationHandlers.ts
  src/page/ItemDetails.tsx
  src/page/Test.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
Labels: fe, release

#66 fix: ExceptionHandler 로그 레벨 변경
  be/src/main/java/kr/codesquad/core/error/GlobalExceptionHandler.java
Labels: fix

#72 chore: dummy 용 data.sql 작성 #70
  be/src/main/resources/data.sql
Labels: chore

#74 fix: requestDto 에 기본 생성자 추가
  be/src/main/java/kr/codesquad/favorite/dto/request/FavoriteUpdateRequest.java
Labels: fix

#76 Dev
  src/api/endPoint.ts
  src/api/fetchers/itemDetailsFetcher.ts
  src/api/fetchers/itemFetcher.ts
  src/api/queries/useItemDetailsQuery.ts
  src/api/queries/useItemQuery.ts
  src/components/Layout.tsx
  src/components/ProductItem.tsx
  src/hooks/useInput.ts
  src/mocks/itemDetailsHandlers.ts
  src/mocks/itemsHandlers.ts
  src/page/Favorites.tsx
  src/page/ItemDetails.tsx
  src/page/auth/ProfileButton.tsx
  src/page/home/Home.tsx
  src/page/productEditor/CategoryContainer.tsx
  src/page/productEditor/CategorySelectModal.tsx
  src/page/productEditor/LocationDropdown.tsx
  src/page/productEditor/PictureContainer.tsx
  src/page/productEditor/ProductContent.tsx
  src/page/productEditor/ProductEditorPanel.tsx
  src/stores/useProductEditorStore.ts
  src/types.ts
  tsconfig.json
Labels: fe

#77 Infra/cicd fe
  src/api/endPoint.ts
  src/api/fetchers/itemDetailsFetcher.ts
  src/api/fetchers/itemFetcher.ts
  src/api/queries/useItemDetailsQuery.ts
  src/api/queries/useItemQuery.ts
  src/components/Layout.tsx
  src/components/ProductItem.tsx
  src/hooks/useInput.ts
  src/mocks/itemDetailsHandlers.ts
  src/mocks/itemsHandlers.ts
  src/page/Favorites.tsx
  src/page/ItemDetails.tsx
  src/page/auth/ProfileButton.tsx
  src/page/home/Home.tsx
  src/page/productEditor/CategoryContainer.tsx
  src/page/productEditor/CategorySelectModal.tsx
  src/page/productEditor/LocationDropdown.tsx
  src/page/productEditor/PictureContainer.tsx
  src/page/productEditor/ProductContent.tsx
  src/page/productEditor/ProductEditorPanel.tsx
  src/stores/useProductEditorStore.ts
  src/types.ts
  tsconfig.json
Labels: fe, release

#75 chore: release test용 커밋
  be/src/main/java/kr/codesquad/category/dto/response/FavoriteCategoryResponseList.java
  be/src/main/java/kr/codesquad/favorite/service/FavoriteService.java
  be/src/main/java/kr/codesquad/user/controller/UserController.java
  be/src/test/java/kr/codesquad/service/FavoriteServiceTest.java
Labels: be, release

#65 프로필 사진 수정 API 구현
  be/src/main/java/kr/codesquad/core/error/statuscode/FileErrorCode.java
  be/src/main/java/kr/codesquad/image/service/AmazonS3Service.java
  be/src/main/java/kr/codesquad/item/service/ItemService.java
  be/src/main/java/kr/codesquad/user/controller/UserController.java
  be/src/main/java/kr/codesquad/user/dto/response/UpdateProfileImageResponse.java
  be/src/main/java/kr/codesquad/user/entity/User.java
  be/src/main/java/kr/codesquad/user/service/UserService.java
  be/src/main/java/kr/codesquad/util/S3ImageDirectory.java
Labels: feat

#79 fix: 한글 이름 이미지 삭제 안되는 오류 수정 #69
  be/src/main/java/kr/codesquad/image/service/AmazonS3Service.java
Labels: bug, fix

#80 로그아웃 기능 구현
  be/build.gradle
  be/src/main/java/kr/codesquad/auth/controller/AuthController.java
  be/src/main/java/kr/codesquad/core/config/RedisConfig.java
  be/src/main/java/kr/codesquad/core/config/SecurityConfig.java
  be/src/main/java/kr/codesquad/core/filter/AuthorizationFilter.java
  be/src/main/java/kr/codesquad/favorite/repository/FavoriteDslRespository.java
  be/src/main/java/kr/codesquad/item/repository/ItemPaginationRepository.java
  be/src/main/java/kr/codesquad/jwt/entity/UserRefreshToken.java
  be/src/main/java/kr/codesquad/jwt/repository/UserRefreshTokenRepository.java
  be/src/main/java/kr/codesquad/jwt/service/JwtAuthenticationSuccessHandler.java
  be/src/main/java/kr/codesquad/jwt/service/JwtProvider.java
  be/src/main/java/kr/codesquad/jwt/service/JwtService.java
  be/src/main/java/kr/codesquad/redis/RedisProperties.java
  be/src/main/java/kr/codesquad/util/RedisUtil.java
  be/src/test/java/kr/codesquad/service/JwtServiceTest.java
Labels: feat, fix

#83 Dev
  src/App.tsx
  src/api/axios.ts
  src/api/endPoint.ts
  src/api/fetchers/authFetcher.ts
  src/api/fetchers/itemFetcher.ts
  src/api/queries/useItemQuery.ts
  src/api/queries/useLocationQuery.ts
  src/assets/icon/error.svg
  src/assets/icon/success.svg
  src/assets/icon/warning.svg
  src/components/Alert.tsx
  src/components/Badge.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/ProductItem.tsx
  src/components/dropdown/ProductItemDropdown.tsx
  src/components/dropdown/UserLocationDropdown.tsx
  src/components/icon/Icon.tsx
  src/components/icon/icons.ts
  src/components/itemDetails/ImageSlider.tsx
  src/components/itemDetails/ItemDetailsSkeleton.tsx
  src/components/itemDetails/Slide.tsx
  src/components/itemDetails/Slider.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/HomeLocationModal.tsx
  src/components/locations/SignUpLocationModal.tsx
  src/components/toast/Toast.tsx
  src/components/toast/ToastContainer.tsx
  src/main.tsx
  src/mocks/authHandlers.ts
  src/mocks/faker.ts
  src/mocks/itemsHandlers.ts
  src/page/Chatting.tsx
  src/page/Favorites.tsx
  src/page/ItemDetails.tsx
  src/page/SalesList.tsx
  src/page/auth/AuthInput.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/MyAccount.tsx
  src/page/auth/MyProfilePage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
  src/page/productEditor/CategoryContainer.tsx
  src/page/productEditor/LocationDropdown.tsx
  src/page/productEditor/PictureContainer.tsx
  src/page/productEditor/ProductEditorPanel.tsx
  src/router/ProtectedRoute.tsx
  src/stores/useAuthStore.ts
  src/stores/useScreenConfigStore.ts
  src/stores/useToastStore.ts
  src/utils/extractKeyName.ts
Labels: fe

#84 Infra/cicd fe
  src/App.tsx
  src/api/axios.ts
  src/api/endPoint.ts
  src/api/fetchers/authFetcher.ts
  src/api/fetchers/itemFetcher.ts
  src/api/queries/useItemQuery.ts
  src/api/queries/useLocationQuery.ts
  src/assets/icon/error.svg
  src/assets/icon/success.svg
  src/assets/icon/warning.svg
  src/components/Alert.tsx
  src/components/Badge.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/ProductItem.tsx
  src/components/dropdown/ProductItemDropdown.tsx
  src/components/dropdown/UserLocationDropdown.tsx
  src/components/icon/Icon.tsx
  src/components/icon/icons.ts
  src/components/itemDetails/ImageSlider.tsx
  src/components/itemDetails/ItemDetailsSkeleton.tsx
  src/components/itemDetails/Slide.tsx
  src/components/itemDetails/Slider.tsx
  src/components/locations/AddLocation.tsx
  src/components/locations/HomeLocationModal.tsx
  src/components/locations/SignUpLocationModal.tsx
  src/components/toast/Toast.tsx
  src/components/toast/ToastContainer.tsx
  src/main.tsx
  src/mocks/authHandlers.ts
  src/mocks/faker.ts
  src/mocks/itemsHandlers.ts
  src/page/Chatting.tsx
  src/page/Favorites.tsx
  src/page/ItemDetails.tsx
  src/page/SalesList.tsx
  src/page/auth/AuthInput.tsx
  src/page/auth/LoginPage.tsx
  src/page/auth/MyAccount.tsx
  src/page/auth/MyProfilePage.tsx
  src/page/auth/SignUpPanel.tsx
  src/page/home/CategoryFilterPanel.tsx
  src/page/home/Home.tsx
  src/page/productEditor/CategoryContainer.tsx
  src/page/productEditor/LocationDropdown.tsx
  src/page/productEditor/PictureContainer.tsx
  src/page/productEditor/ProductEditorPanel.tsx
  src/router/ProtectedRoute.tsx
  src/stores/useAuthStore.ts
  src/stores/useScreenConfigStore.ts
  src/stores/useToastStore.ts
  src/utils/extractKeyName.ts
Labels: fe, release

#82 fix: 요청 온 파일이 없으면 디폴트 이미지로 업데이트 #64
  be/src/main/java/kr/codesquad/user/controller/UserController.java
  be/src/main/java/kr/codesquad/user/service/UserService.java
Labels: fix

#85 채팅 기능 구현
  be/build.gradle
  be/src/main/java/kr/codesquad/chat/controller/ChatController.java
  be/src/main/java/kr/codesquad/chat/dto/ChatMapper.java
  be/src/main/java/kr/codesquad/chat/dto/request/ChatMessageRequest.java
  be/src/main/java/kr/codesquad/chat/dto/request/ChatRoomCreateRequest.java
  be/src/main/java/kr/codesquad/chat/dto/request/SendMessageRequest.java
  be/src/main/java/kr/codesquad/chat/dto/response/ChatRoomCreateResponse.java
  be/src/main/java/kr/codesquad/chat/entity/ChatMessage.java
  be/src/main/java/kr/codesquad/chat/entity/ChatRoom.java
  be/src/main/java/kr/codesquad/chat/repository/ChatMessageRepository.java
  be/src/main/java/kr/codesquad/chat/repository/ChatRoomRepository.java
  be/src/main/java/kr/codesquad/chat/repository/MessageRepository.java
  be/src/main/java/kr/codesquad/chat/service/ChatService.java
  be/src/main/java/kr/codesquad/chat/service/RedisSubscriber.java
  be/src/main/java/kr/codesquad/core/config/RedisConfig.java
  be/src/main/java/kr/codesquad/core/config/SecurityConfig.java
  be/src/main/java/kr/codesquad/core/config/SecurityWebSocketConfig.java
  be/src/main/java/kr/codesquad/core/config/WebSocketConfig.java
  be/src/main/java/kr/codesquad/core/filter/AuthorizationFilter.java
  be/src/main/java/kr/codesquad/core/filter/WebSocketInterceptor.java
  be/src/main/java/kr/codesquad/item/repository/ItemPaginationRepository.java
  be/src/main/java/kr/codesquad/item/service/ItemService.java
  be/src/test/java/kr/codesquad/service/ItemServiceTest.java
Labels: feat
